### PR TITLE
Fix file names in generated code for auto_route snippets

### PR DESCRIPTION
**Pull request by InMatrix**
I regenerated code from the auto_route snippets to fix file names referenced in the original generated code.

### CODE REVIEW

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by Milad-Akarie** [comment]
Hello @chunhtai I need to ask some questions, I couldn't find you on discord. Is there a way I can communicate with you?

**Comment by chunhtai** [comment]
my user id is chunhtai in discord, you can also ping me on router-research channel

**Comment by Milad-Akarie** [comment]
I can't find neither, could you share an invitation link or give me your 4 digits

**Comment by chunhtai** [comment]
chunhtai#7571

**Pull request merged**
