### PR TITLE
Navi 0.2.0 code snippets

### PR DESCRIPTION
**Pull request by nguyenxndaidev**

### CODE REVIEW

**Comment by InMatrix** [comment]
@nguyenxndaidev Is this PR ready for review? I can do a shallow review (i.e., checking whether the demos match the reference implementations in Navigator 2.0) and merge them.

**Comment by nguyenxndaidev** [comment]
@InMatrix yes, it's ready. Thanks for checking my PR.

**Comment by InMatrix** [comment]
Okay, I checked the behavior of the demos and found only 1 issue. The skipping stacks demo required me to click the browser's back button more than once to get back to the previous screen. Please see this screen recording:


https://user-images.githubusercontent.com/348942/116470067-c9eee680-a827-11eb-8c9f-31436b4087e4.mov

I'd be happy to merge the snippets as is with a TODO comment in skipping_stacks_navi.dart or wait until you fix this issue.

**Comment by nguyenxndaidev** [comment]
Hi @InMatrix, please wait for me to check it first if I can do a quick hotfix. Otherwise I'll let you know to merge without the fix.
Thanks a lot for your time!

**Comment by nguyenxndaidev** [comment]
Hi, I fixed it locally. I am publishing version 0.2.1 with the hotfix now.

**Comment by nguyenxndaidev** [comment]
@InMatrix Fixed now. Could you please check again?

**Review by InMatrix — APPROVED** [review]

**Pull request merged**
