### PR TITLE
Update the metadata for the survey pilot testing #2

### PR DESCRIPTION
**Pull request by jayoung-lee**
Updated: ID, date, URL, condition, etc.
TODO: update the description if needed

### CODE REVIEW

**Review by eliasyishak — APPROVED** [review]
Sorry for the delayed response on this!

But LGTM, just curious though.. i'm just realizing that for us to use the flutter channel as a conditional, I am assuming that the channel that is reported by Flutter is `beta`.

Is this always how Flutter will report that channel? ie. can it vary in casing such as `BETA`, `Beta`, etc?

**Review by eliasyishak — CHANGES_REQUESTED** [review]
Oh wait, you may want to also change the snooze period to be more than 5 minutes right?

**Comment by jayoung-lee** [comment]
Updated!

**Review by eliasyishak — APPROVED** [review]
LGTM :)

**Comment by jayoung-lee** [comment]
Thank you :D

**Pull request merged**
