### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Gene-Dana**
Added in flow_builder

### CODE REVIEW

**Review by jackkim9 — APPROVED** [review]
Thanks @Gene-Dana for the PR! The table was breaking for me, so I made some minor adjustments. Otherwise, this looks good.

@felangel, please feel free to comment if you leave your comments if you need any adjustments. 

CC: #26

**Comment by InMatrix** [comment]
@Gene-Dana Multiple scenarios have an `*` which indicates "in progress." To be consistent, we should not check off a scenario until it's supported by the package. Could you update your PR? 

For scenarios you believe `flow_builder` already supports, please include pointers to relevant documentation or examples so we can verify them. Thanks!

**Review by InMatrix — CHANGES_REQUESTED** [review]
Please uncheck "in progress" scenarios and provide supporting evidence (e.g., documentation or examples) for supported scenarios.

**Review by Gene-Dana — COMMENTED** [review]
Can do

**Review by Gene-Dana — COMMENTED** [review]
not a problem

**Comment by Gene-Dana** [comment]
> For scenarios you believe `flow_builder` already supports, please include pointers to relevant documentation or examples so we can verify them. Thanks!

Is this the correct place to add the supporting evidence? https://github.com/flutter/uxr/issues/13

**Comment by InMatrix** [comment]
@Gene-Dana You can just leave that as a comment for this PR.

**Comment by Gene-Dana** [comment]
Login/Logout/Sign-Up Routing - Routing with Validation https://github.com/felangel/flow_builder/blob/master/example/lib/authentication_flow/authentication_flow.dart

**Comment by Gene-Dana** [comment]
Nested Routing
https://github.com/definitelyokay/multiweather

**Comment by Gene-Dana** [comment]
Skipping Stacks
https://github.com/felangel/flow_builder/blob/master/example/lib/onboarding_flow/onboarding_flow.dart

**Comment by Gene-Dana** [comment]
These are the complete examples that I believe demonstrate these particular cases ! When URL parsing support is added, is this the appropriate place to put the new supporting evidence?

**Comment by InMatrix** [comment]
@Gene-Dana Thanks for updating the PR and adding the links. I have a few questions:

- In the nested routing example you linked to, it's unclear whether `flow_builder` is responsible for setting up nested routing or it can work with a nested routing setup created by using another API. Could you clarify this? 
- Would you mind pointing to an example of implementing "custom transition animations" with `flow_builder`?

**Comment by felangel** [comment]
@Gene-Dana thanks so much for taking the time to put together this proposal! I really appreciate it 🙏 💙 

> @Gene-Dana Thanks for updating the PR and adding the links. I have a few questions:
> 
> * In the nested routing example you linked to, it's unclear whether `flow_builder` is responsible for setting up nested routing or it can work with a nested routing setup created by using another API. Could you clarify this?
> * Would you mind pointing to an example of implementing "custom transition animations" with `flow_builder`?

FlowBuilder currently supports nested routing in the sense that you can have FlowBuilders within other FlowBuilders. It can also work in the context of a nested setup created by using other APIs.

Custom transition animations can be seen in the [onboarding example](https://github.com/felangel/flow_builder/blob/9c8e0e64b24881142c3c17b2e49cf71603fb846f/example/lib/onboarding_flow/onboarding_flow.dart#L259).

Let me know if that helps!

**Review by Gene-Dana — COMMENTED** [review]
👍🏼

**Comment by InMatrix** [comment]
@Gene-Dana @felangel Thank you both!

**Review by InMatrix — APPROVED** [review]

**Pull request merged**
