### PR TITLE
Migrating from GitHub Actions -> Cloud Build

### PR DESCRIPTION
**Pull request by khanhnwin**
- [X] cloudbuild.yaml to upload the surveys folder contents to a Google Cloud Storage bucket. 
- [X] remove GCS upload GitHub Action 
- [X] Verify upload works with my test bucket, `gs://khanhs-test-bucket/` See build here: [go/flutter-uxr-surveys-test-upload](go/flutter-uxr-surveys-test-upload)
- [X] Swap `gs://khanhs-test-bucket/` for the prod UXR bucket `gs://flutter-uxr/`.

### CODE REVIEW

**Review by drewroengoogle — APPROVED** [review]

**Comment by khanhnwin** [comment]
Working build with my test bucket: [go/flutter-uxr-surveys-test-upload](go/flutter-uxr-surveys-test-upload)

**Comment by khanhnwin** [comment]
Waiting for confirmation from JaYoung to make sure I can land final bucket switch!

**Comment by khanhnwin** [comment]
Confirmed with JaYoung!

**Comment by khanhnwin** [comment]
Confirmed this PR works! Switched Cloud Build trigger to master branch.

**Pull request merged**
