### PR TITLE
Add Qlevar Router code samples

### PR DESCRIPTION
**Pull request by SchabanBo**
Here are the code snippets for qlevar_router. you can find them in [qr_samples](https://github.com/SchabanBo/qr_samples) too.

### CODE REVIEW

**Comment by SchabanBo** [comment]
@googlebot I signed it!

**Comment by Hixie** [comment]
@InMatrix Is this obsolete?

**Comment by SchabanBo** [comment]
@InMatrix That would be great. Thanks

**Comment by SchabanBo** [comment]
@InMatrix I have fixed these two issues and added the nested routing example.
At the time I added the qlevar router examples. there was no router example for the nested routing.
thanks for reminding

**Comment by InMatrix** [comment]
Thanks for updating the PR. I confirm that the bug in the skip stacks example has been fixed. 

For the deep linking by path parameter example, I still don't see the in-app back button when going to a book page directly (see the screenshot below):

image

For the nested routing example, the tabs won't switch when the URL has changed after clicking the back button in the browser. I attached a screencast below: 

Uploading Screen Recording 2021-10-30 at 2.32.40 PM.mov…

**Comment by SchabanBo** [comment]
@InMatrix sorry about that. I forgot to add the tab listener.

**Review by InMatrix — APPROVED** [review]
Thanks for updating this PR. I confirm that all examples produce intended results.

**Comment by InMatrix** [comment]
@johnpryan Do you know how to unblock this PR? It's blocked by a signing issue I'm not familiar with: "The base branch requires all commits to be signed."

**Comment by johnpryan** [comment]
I believe Flutter organization PRs require commits to be signed now. Pull request authors need to follow the steps described in the [Commit signature verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification) page from the GitHub docs.

**Pull request merged**
