### PR TITLE
[VRouter] simplifying dynamic linking scenario

### PR DESCRIPTION
**Pull request by lulupointu**
This is a small commit to simplify the dynamic linking scenario base on https://github.com/flutter/uxr/issues/40#issuecomment-821306338.

I know you don't want to take Dynamic Linking into account for the final review but since this repo is also meant for devs to come and compare the different scenario I think this will be useful. In any case, changes are small so it should not take too long to review.

### CODE REVIEW

**Comment by johnpryan** [comment]
@jackkim9 is it okay to change the snippets after the walkthrough study?

**Comment by lulupointu** [comment]
Note that these change concern more the Flutter logic than vrouter per say. The `routes` are the same, I mainly remove the `onCreate` function which was causing trouble during the study (which makes sense since I should not have used it in the first place)

**Comment by nguyenxndaidev** [comment]
I have some questions regarding how should we write the code snippets for packages.
* What's the purposes of the snippets in details?
* Should we keep changes minimal from the original? Or should we make the most optimized code for each package?

**Comment by InMatrix** [comment]
@nguyenxndaidev These are good questions. When we publish study results, we should identify a specific commit for each snippet used in the study. The findings will have a shelf life, since those packages will evolve. IMO, package authors can continue updating their snippets in this repo, but they should provide a summary of changes and explain whether any of the changes are intended to address findings from the study. No changes should affect the demo's behavior though.

**Comment by InMatrix** [comment]
@lulupointu Would you still be interested in merging this PR? The folder structured has changed, so if you'd like to merge this PR, please update it to match the structure on master. Thanks.

**Comment by InMatrix** [comment]
A separate PR might be cleaner. Thanks.

**Comment by InMatrix** [comment]
@lulupointu I'm closing this PR for now. Feel free to open a new one when you're ready for updating your snippets. Thanks!

**Pull request closed without merging**
